[package]
name = "solana"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
engine = { path = "../engine" }
tools = { path = "../tools" }

ahash = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
futures-util = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
simd-json = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

bytemuck = { version = "1.24.0" }
solana-client = { version = "3.1.8" }
solana-sdk = { version = "3.0.0" }
yellowstone-grpc-client = { version = "11.0.0" }
yellowstone-grpc-proto = { version = "11.0.0" }

[lints]
workspace = true
